name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet restore src/S1VoiceChat/S1VoiceChat.csproj
      - run: dotnet build src/S1VoiceChat/S1VoiceChat.csproj -c CrossCompat --no-restore
      - run: dotnet build src/S1VoiceChat/S1VoiceChat.csproj -c MonoMelon --no-restore
      - run: dotnet build src/S1VoiceChat/S1VoiceChat.csproj -c Il2CppMelon --no-restore
